[package]
name = "radarflow2"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dma and memory
memflow = "=0.2.0-beta10"
dataview = "1.0.1"

# logging 
log = "0.4.19"
env_logger = "0.10.0"

# error handling
anyhow = "1.0.72"

# tokio
tokio = { version = "1.29.1", features = ["full"] }
field_types = "1.1.0"
futures-util = "0.3.28"

# serde
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
toml = "0.7.6"

# networking
axum = { version = "0.6.20", features = ["ws"] }
tower-http = { version = "0.4.3", features = ["fs"] }
tower = "0.4.13"
tokio-timerfd = "0.2.0"

# other
local-ip-address = "0.5.4"
enum-primitive-derive = "0.2.2"
num-traits = "0.2.16"
clap = { version = "4.3.19", features = ["derive", "string"] }
simple_logger = "4.2.0"
chrono = "0.4.26"

[build-dependencies]
reqwest = { version = "0.11.18", features = ["blocking"] }
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl", "rustc", "si"] }
